### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by saskra** [kynnemall/superviolin#1]
https://github.com/kynnemall/superviolin/blob/6bf534f40fd912e3c49cbdcecce65baf99e06727/superviolin/superviolin/res/args.txt#L9

Thank you for this beautiful package! But where can I find the documentation mentioned? (Unfortunately I can't access the paper).

**Comment by kynnemall** [comment]
I can upload a copy of the documentation in PDF format

**Comment by kynnemall** [comment]
Just uploaded a copy of the documentation as a PDF
